version: "3"

services:
  contacts:
   image: edbrannin/contacts
   volumes:
      - config:config
      - db:db
   restart: always
   ports:
       - "127.0.0.1:5000:5000"

volumes:
    - config
    - db
